import type { Metadata } from "next";
import { Unbounded, Ubuntu_Mono } from "next/font/google";
import Grainient from "@/components/ui/Grainient/Grainient";

import "@/styles/globals.css";
import Navbar from "@/components/ui/Navbar";

const ubuntuMono = Ubuntu_Mono({
  variable: "--font-ubuntu-mono",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${ubuntuMono.variable} ${unbounded.variable} antialiased min-h-screen`}
      >
        <Grainient
          color1="#1a1919"
          color2="#1a1919"
          color3="#1a1919"
          timeSpeed={0.25}
          colorBalance={0}
          warpStrength={1}
          warpFrequency={5}
          warpSpeed={2}
          warpAmplitude={50}
          blendAngle={0}
          blendSoftness={0.05}
          rotationAmount={500}
          noiseScale={1.5}
          grainAmount={0.45}
          grainScale={1.5}
          grainAnimated={false}
          contrast={1.5}
          gamma={1}
          saturation={1}
          centerX={0}
          centerY={0}
          zoom={0.9}
          className="h-full w-full -z-10 fixed inset-0"
        />
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
